main: ${project.groupId}.${project.artifactId}.${project.name}
name: ${project.artifactId}
version: ${project.version}
load: STARTUP
author: xt449
api-version: '1.16'

permissions:
  minecraftdiscordbot.command.link:
    default: true
#  minecraftdiscordbot.command.syncroles:
#    default: op

commands:
  link:
    aliases: [pair]
    description: Link your Minecraft and Discord accounts.
    usage: /<command> <discord username#tag>
    permission: minecraftdiscordbot.command.link
#  syncroles:
#    aliases: [forcesync]
#    description: Force a update of all Discord roles for users with paired accounts.
#    usage: /<command>
#    permission: minecraftdiscordbot.command.syncroles
