main: ${project.groupId}.${project.artifactId}.${project.name}
name: ${project.name}
version: ${project.version}
load: STARTUP
author: xt449
api-version: '1.16'

permissions:
  minecraftdiscordbot.command.link:
    default: true
  minecraftdiscordbot.command.whois:
    default: true
#  minecraftdiscordbot.command.syncroles:
#    default: op

commands:
  link:
    aliases: [pair]
    description: Link your Minecraft and Discord accounts.
    usage: /<command> <discord tag>
    permission: minecraftdiscordbot.command.link
  whois:
    aliases: [who]
    description: Get the Discord tag of a player
    usage: /<command> <player>
    permission: minecraftdiscordbot.command.whois
#  syncroles:
#    aliases: [forcesync]
#    description: Force a update of all Discord roles for users with paired accounts.
#    usage: /<command>
#    permission: minecraftdiscordbot.command.syncroles
